---
title: "Introducción"
author: "Felipe Ignacio Moya González"
date: "09-11-2020"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h2> 1. Contexto </h2>

<p> Actualmente la premier league de inglaterra es la liga de fútbol más competitiva del mundo _BUSCAR FUENTE_, pues desde hace varios años que los equipos que salen campeones varian cada temporada. Y siempre hay algún equipo que da la sorpresa. El Manchester City, equipo que juega en la premier league actualmente, ha destacado los últimos años, ganando varios títulos y mostrando una gran mejoría con respecto a años anteriores, donde no solía destacar. A lo largo de este informe, se analizará el desempeño del equipo Manchester City entre las temporadas 2014 y 2019, para luego ver si hay algo que el equipo deba hacer mejor a futuro para aspirar a salir campeón. </p>

<hr>

<h2> 2. Problema / relevancia / necesidad </h2>

<p> En este análisis se tratará de encontrar las debilidades del equipo para poder cubrirlas y luego poder mejorarlas a futuro. Esas debilidades pueden influir mucho al desempeño del equipo, por lo que entenderlas y mejorarlas es muy importante para que el Manchester City pueda llegar a ser campeón a futuro.</p>

<hr>

<h2> 3. Foco </h2>

<p> Es por esto que en este informe se revisarán los factores que más influyeron en el desempeño del equipo, y se enfocará en determinar a grandes rasgos las falencias que el equipo ha tenido en estos últimos años, para poder mejorarlas. </p>

<hr>

<h2> 4. Carta de navegación </h2>

<p> El informe se desarrollará en cuatro secciones: primero se hará una pequeña introducción para que el lector entre en contexto con el tema y con alguna información que no se analizó pues no se encuentra en la base de datos, después se analizarán los goles marcados y recibidos por el equipo en cada temporada a través de gráficos, luego se hará una comparación de los resultados obtenidos por el equipo contra los __big six__ (incluir un link que lleve a una explicación de que son los big six) en cada temporada, y ver si esto influyó en que el equipo haya salido campeón, por último se sacarán conclusiones de estos resultados, para ver cuales son las debilidades que debe cubrir el equipo. 
Cabe recalcar que en este análisis no se usa toda la información que influye en los resultados de cada partido pues esta información va más allá de lo que se puede analizar en esta base de datos. Por lo que si se quisiera obtener conclusiones más precisas se podría hacer un análisis que abarque más años y que además use otras variables que no están en esta base de datos, como por ejemplo los jugadores que tiene el equipo, las lesiones, etc. </p>











